### ISSUE TITLE
Add lazy loader for images and videos

### ISSUE THREAD

**Issue by Icuyno** [Icuyno/Portfolio#11]
## Issue Description
The website does not implement lazy loading for images potentially impacting performance.

### Steps to Reproduce:
1. Access the website and observe the loading behaviour of images.

### Expected Result:
Images should be loaded lazily for improved performance.

### Actual Result:
Lazy loading is not implemented.

**Comment by Icuyno** [comment]
### Tasks

- [ ] Implement lazy loading for both images and videos on the website.
- [ ] Test the website's performance to ensure efficient loading of images and videos.
- [ ] The transition is smooth the images don't load top-down
- [ ] Ensure that preloader content upright and centered

**Comment by Icuyno** [comment]
Completed for all project thumbnails and for each image in each artifact page.

[Link to commit](https://github.com/Icuyno/Portfolio/commit/d6fa737ecc9e873369f979d4c227ad266c59eaff)
