### ISSUE TITLE
Add a preloader

### ISSUE THREAD

**Issue by Icuyno** [Icuyno/Portfolio#7]

**Comment by Icuyno** [comment]
- [ ] Confirm the presence of a preloader when accessing the website
- [ ] Validate that the preloader disappears once the page is fully loaded.
- [ ] The preloader content is appearing correctly. Size and position on the site is upright and centered

**Comment by Icuyno** [comment]
### Tasks

- [x] Confirm the presence of a preloader when accessing the website
- [x] Validate that the preloader disappears once the page is fully loaded.
- [x] The preloader content is appearing correctly. Size and position on the site is upright and centered

**Comment by Icuyno** [comment]
Added preloader

[Link to commit](https://github.com/Icuyno/Portfolio/commit/4ca0cc0cd681a3025ced5dbd905b0c62a9491a5c)
