### ISSUE TITLE
#9

### ISSUE THREAD

**Issue by Icuyno** [Icuyno/Portfolio#9]

**Comment by Icuyno** [comment]
- [ ] Add a GitHub link to the appropriate section on the website
- [ ] Confirm that the GitHub link directs users to the correct repository

**Comment by Icuyno** [comment]
### Tasks

- [ ] Add a GitHub link to the appropriate section on the website
- [ ] Confirm that the GitHub link directs users to the correct repository

**Comment by Icuyno** [comment]
![new-github-link](https://github.com/Icuyno/Portfolio/assets/115044993/375a6556-8a26-471c-83ad-03703f98d688)

The issue is illustrated in the screenshot above. The button is not functioning as expected.
